import { useState, useEffect } from "react";
import { useParams, useNavigate, useLocation } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LoanTrackerFull, LoanTrackerDominos, statusConfig, LoanStatus } from "@/components/loan/LoanTracker";
import { FullApplicationForm } from "@/components/loan/FullApplicationForm";
import { loansApi, documentsApi, paymentsApi, opsApi, Loan, NeedsListItem, SoftQuote } from "@/lib/api";
import { 
  ArrowLeft, Building2, DollarSign, FileText, Download, CreditCard, 
  CheckCircle2, AlertCircle, Upload, Shield, FileCheck, Calendar, ClipboardCheck
} from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { Navbar } from "@/components/layout/Navbar";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";

export default function LoanDetail() {
  const { loanId } = useParams<{ loanId: string }>();
  const navigate = useNavigate();
  const location = useLocation();
  const { user } = useAuth();
  const [loan, setLoan] = useState<Loan | null>(null);
  const [needsList, setNeedsList] = useState<NeedsListItem[]>([]);
  const [closingChecklist, setClosingChecklist] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [showCreditAuth, setShowCreditAuth] = useState(false);
  const [showAppraisalPayment, setShowAppraisalPayment] = useState(false);
  const [creditConsent, setCreditConsent] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);

  // Determine if this is an operations/admin view
  const isOpsView = location.pathname.startsWith('/ops') || (user?.role === 'operations' || user?.role === 'admin');

  useEffect(() => {
    if (loanId) {
      loadLoanData();
    }
  }, [loanId]);

  const loadLoanData = async () => {
    try {
      if (isOpsView) {
        // Use operations API for ops/admin users
        const [loanRes, checklistRes] = await Promise.all([
          opsApi.getLoan(loanId!),
          opsApi.getClosingChecklist(loanId!).catch(() => ({ checklist: [] }))
        ]);
        setLoan(loanRes.loan);
        setNeedsList(loanRes.needsList || []);
        setClosingChecklist(checklistRes.checklist || []);
      } else {
        // Use borrower API for regular users
        const [loanRes, needsRes, checklistRes] = await Promise.all([
          loansApi.get(loanId!),
          documentsApi.getNeedsList(loanId!),
          loansApi.getClosingChecklist(loanId!).catch(() => ({ checklist: [] }))
        ]);
        setLoan(loanRes.loan);
        setNeedsList(needsRes.needsList);
        setClosingChecklist(checklistRes.checklist || []);
      }
    } catch (error: any) {
      toast.error(error.message || "Failed to load loan details");
      if (isOpsView) {
        navigate("/ops");
      } else {
        navigate("/dashboard");
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleCreditAuth = async () => {
    if (!creditConsent) {
      toast.error("Please provide consent to proceed");
      return;
    }

    setIsProcessing(true);
    try {
      await loansApi.creditAuth(loanId!);
      toast.success("Credit authorization completed");
      setShowCreditAuth(false);
      await loadLoanData();
      
      // Quote should already be generated by admin approval, just reload
      await loadLoanData();
    } catch (error: any) {
      toast.error(error.message || "Credit authorization failed");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSignTermSheet = async () => {
    setIsProcessing(true);
    try {
      await loansApi.signTermSheet(loanId!);
      toast.success("Term sheet signed! Needs list will be sent to your email.");
      await loadLoanData();
    } catch (error: any) {
      toast.error(error.message || "Failed to sign term sheet");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleAppraisalPayment = async () => {
    setIsProcessing(true);
    try {
      const paymentRes = await paymentsApi.createAppraisalIntent(loanId!);
      
      if (paymentRes.mockMode) {
        // Mock payment for development
        await paymentsApi.confirmPayment(loanId!, paymentRes.clientSecret.split('_')[2]);
        toast.success("Appraisal payment completed (mock mode)");
        setShowAppraisalPayment(false);
        await loadLoanData();
      } else {
        // In production, integrate Stripe Elements here
        toast.info("Payment processing - Stripe integration needed");
      }
    } catch (error: any) {
      toast.error(error.message || "Payment failed");
    } finally {
      setIsProcessing(false);
    }
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat("en-US", {
      style: "currency", currency: "USD", minimumFractionDigits: 0,
    }).format(amount);
  };

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gold-500"></div>
      </div>
    );
  }

  if (!loan) {
    return null;
  }

  const statusConfigItem = statusConfig[loan.status as LoanStatus] || { label: loan.status, color: "bg-gray-100 text-gray-700" };
  const quote: SoftQuote | null = loan.soft_quote_data || null;

  return (
    <div className="min-h-screen bg-muted/30">
      <Navbar variant="light" />
      
      <div className="container mx-auto px-4 py-8">
        <Button variant="ghost" onClick={() => navigate(isOpsView ? "/ops" : "/dashboard")} className="mb-6">
          <ArrowLeft className="w-4 h-4 mr-2" /> {isOpsView ? 'Back to Pipeline' : 'Back to Dashboard'}
        </Button>

        <div className="grid lg:grid-cols-3 gap-6">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Loan Tracker - Domino's Style */}
            <Card className="border-gold-500/20 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileCheck className="w-5 h-5 text-gold-600" />
                  Loan Progress Tracker
                </CardTitle>
                <CardDescription>
                  Track your loan application through each stage
                </CardDescription>
              </CardHeader>
              <CardContent>
                <LoanTrackerDominos currentStatus={loan.status as LoanStatus} />
              </CardContent>
            </Card>

            {/* Loan Header */}
            <Card>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle className="text-2xl">{loan.loan_number}</CardTitle>
                    <CardDescription className="mt-2">
                      {loan.property_address}, {loan.property_city}, {loan.property_state} {loan.property_zip}
                    </CardDescription>
                  </div>
                  <Badge className={statusConfigItem.color}>{statusConfigItem.label}</Badge>
                </div>
              </CardHeader>
              <CardContent>
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm text-muted-foreground">Loan Amount</p>
                    <p className="text-2xl font-bold">{formatCurrency(loan.loan_amount || 0)}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Property Value</p>
                    <p className="text-xl font-semibold">{formatCurrency(loan.property_value || 0)}</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">LTV</p>
                    <p className="text-xl font-semibold">{loan.requested_ltv}%</p>
                  </div>
                  <div>
                    <p className="text-sm text-muted-foreground">Transaction Type</p>
                    <p className="text-lg">{loan.transaction_type?.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Action Cards */}
            {loan.status === "quote_requested" && (
              <Card className="border-yellow-500/50 bg-yellow-500/5">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-yellow-600">
                    <Shield className="w-5 h-5" />
                    {isOpsView ? "Quote Request - Action Required" : "Quote Request Pending Approval"}
                  </CardTitle>
                  <CardDescription>
                    {isOpsView 
                      ? "This loan request is awaiting your approval to generate a quote. Review the loan details and approve to proceed."
                      : "Your loan request has been submitted and is awaiting admin approval. You will be notified once your quote is approved."
                    }
                  </CardDescription>
                </CardHeader>
                {isOpsView && (
                  <CardContent>
                    <Button 
                      variant="default"
                      className="bg-green-600 hover:bg-green-700 text-white w-full"
                      onClick={async () => {
                        setIsProcessing(true);
                        try {
                          await opsApi.approveQuote(loanId!);
                          toast.success(`Quote approved for ${loan.loan_number}`);
                          await loadLoanData();
                        } catch (error: any) {
                          console.error('Approve quote error:', error);
                          toast.error(error.message || 'Failed to approve quote');
                        } finally {
                          setIsProcessing(false);
                        }
                      }}
                      disabled={isProcessing}
                    >
                      <CheckCircle2 className="w-4 h-4 mr-2" />
                      {isProcessing ? "Approving..." : "Approve Quote & Generate"}
                    </Button>
                  </CardContent>
                )}
              </Card>
            )}
            
            {/* Show action card for soft_quote_issued status - allow signing term sheet */}
            {/* More flexible condition: check status OR if quote is generated but not signed */}
            {((loan.status === "soft_quote_issued" || 
               loan.status === "soft_quote" || 
               (loan.soft_quote_generated && !loan.term_sheet_signed)) && 
               !loan.term_sheet_signed && 
               !isOpsView) && (
              <Card className="border-cyan-500/50 bg-cyan-500/5 shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-cyan-700">
                    <FileCheck className="w-5 h-5" />
                    Quote Approved - Review & Sign Term Sheet
                  </CardTitle>
                  <CardDescription className="text-base">
                    Your quote has been approved! Review your quote details below and sign the term sheet to proceed to the next step.
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                  {quote && (
                    <div className="p-4 bg-white rounded-lg border-2 border-cyan-200">
                      <div className="grid md:grid-cols-2 gap-4 mb-4">
                        <div>
                          <p className="text-sm text-muted-foreground">Interest Rate Range</p>
                          <p className="text-2xl font-bold text-gold-600">{quote.rateRange}</p>
                        </div>
                        <div>
                          <p className="text-sm text-muted-foreground">Estimated Monthly Payment</p>
                          <p className="text-xl font-semibold">{formatCurrency(quote.estimatedMonthlyPayment)}</p>
                        </div>
                      </div>
                      {quote.dscr && (
                        <div className="mb-4">
                          <p className="text-sm text-muted-foreground">DSCR Ratio</p>
                          <p className="text-lg font-semibold">{quote.dscr.toFixed(2)}x</p>
                        </div>
                      )}
                      <div className="pt-4 border-t">
                        <p className="text-sm text-muted-foreground mb-2">Total Estimated Closing Costs</p>
                        <p className="text-xl font-bold">{formatCurrency(quote.totalClosingCosts)}</p>
                      </div>
                    </div>
                  )}
                  {!quote && loan.soft_quote_data && (
                    <div className="p-4 bg-white rounded-lg border-2 border-cyan-200">
                      <p className="text-sm text-muted-foreground mb-2">Quote Details</p>
                      <p className="text-lg">Your soft quote has been generated. Please review and sign the term sheet to continue.</p>
                    </div>
                  )}
                  <div className="flex flex-col sm:flex-row gap-3 pt-2">
                    {loan.term_sheet_url && (
                      <a href={loan.term_sheet_url} target="_blank" rel="noopener noreferrer" className="flex-1">
                        <Button variant="outline" className="w-full">
                          <Download className="w-4 h-4 mr-2" /> Download Term Sheet PDF
                        </Button>
                      </a>
                    )}
                    <Button 
                      variant="gold" 
                      onClick={handleSignTermSheet} 
                      disabled={isProcessing}
                      className="flex-1 text-lg py-6"
                    >
                      {isProcessing ? (
                        <>
                          <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                          Processing...
                        </>
                      ) : (
                        <>
                          <FileCheck className="w-5 h-5 mr-2" />
                          Sign Term Sheet to Continue
                        </>
                      )}
                    </Button>
                  </div>
                  <p className="text-xs text-muted-foreground text-center pt-2">
                    By signing, you agree to proceed with the loan application process
                  </p>
                </CardContent>
              </Card>
            )}

            {/* Show document upload section if term sheet is signed but status hasn't updated yet */}
            {loan.term_sheet_signed && loan.status !== "needs_list_sent" && loan.status !== "needs_list_complete" && (
              <Card className="border-green-500/50 bg-green-500/5 shadow-lg">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-green-700">
                    <CheckCircle2 className="w-5 h-5" />
                    Term Sheet Signed - Upload Documents
                  </CardTitle>
                  <CardDescription className="text-base">
                    Your term sheet has been signed! Please upload the required documents below to continue with your loan application.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {needsList.length === 0 ? (
                    <div className="p-4 bg-white rounded-lg border space-y-3">
                      <p className="text-muted-foreground">Your needs list is being prepared. You will receive an email shortly with the required documents.</p>
                      <p className="text-sm text-muted-foreground">Please check your email or refresh this page in a few moments.</p>
                      <div className="flex gap-2">
                        <Button 
                          variant="outline" 
                          onClick={async () => {
                            setIsProcessing(true);
                            try {
                              await loadLoanData();
                              toast.success("Page refreshed. If needs list is still empty, the backend may need to be restarted.");
                            } catch (error: any) {
                              toast.error("Failed to refresh");
                            } finally {
                              setIsProcessing(false);
                            }
                          }}
                          disabled={isProcessing}
                          className="flex-1"
                        >
                          {isProcessing ? "Refreshing..." : "Refresh Page"}
                        </Button>
                        {import.meta.env.DEV && (
                          <Button 
                            variant="default"
                            onClick={async () => {
                              setIsProcessing(true);
                              try {
                                // Try to trigger needs list generation by calling sign-term-sheet again
                                // This will check if needs list exists and generate it if not
                                await loansApi.signTermSheet(loanId!);
                                toast.success("Needs list generation triggered. Refreshing...");
                                await loadLoanData();
                              } catch (error: any) {
                                toast.error(error.message || "Failed to generate needs list");
                              } finally {
                                setIsProcessing(false);
                              }
                            }}
                            disabled={isProcessing}
                            className="flex-1 bg-blue-600 hover:bg-blue-700"
                          >
                            {isProcessing ? "Generating..." : "Generate Needs List"}
                          </Button>
                        )}
                      </div>
                    </div>
                  ) : (
                    <div className="space-y-3">
                      {needsList.map((item) => (
                        <div key={item.id} className="flex items-center justify-between p-3 bg-white border rounded-lg">
                          <div className="flex-1">
                            <p className="font-medium">{item.document_type}</p>
                            <p className="text-sm text-muted-foreground">{item.description}</p>
                            {item.document_count > 0 && (
                              <p className="text-xs text-green-600 mt-1">
                                {item.document_count} file(s) uploaded
                              </p>
                            )}
                          </div>
                          <label>
                            <input
                              type="file"
                              className="hidden"
                              onChange={async (e) => {
                                const file = e.target.files?.[0];
                                if (file && loanId) {
                                  try {
                                    await documentsApi.upload(loanId, file, item.id);
                                    toast.success("Document uploaded successfully");
                                    await loadLoanData();
                                  } catch (error: any) {
                                    toast.error(error.message || "Upload failed");
                                  }
                                }
                              }}
                            />
                            <Button variant="outline" size="sm" asChild>
                              <span>
                                <Upload className="w-4 h-4 mr-2" /> Upload
                              </span>
                            </Button>
                          </label>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {/* Debug card - Show loan status info in development mode */}
            {import.meta.env.DEV && (
              <Card className="border-gray-300 bg-gray-50">
                <CardHeader>
                  <CardTitle className="text-sm">🔍 Debug Info (Development Only)</CardTitle>
                </CardHeader>
                <CardContent className="text-xs space-y-1 font-mono">
                  <p><strong>Status:</strong> <span className="text-blue-600">{loan.status}</span></p>
                  <p><strong>Soft Quote Generated:</strong> {loan.soft_quote_generated ? '✅ Yes' : '❌ No'}</p>
                  <p><strong>Term Sheet Signed:</strong> {loan.term_sheet_signed ? '✅ Yes' : '❌ No'}</p>
                  <p><strong>Has Quote Data:</strong> {loan.soft_quote_data ? '✅ Yes' : '❌ No'}</p>
                  <p><strong>Term Sheet URL:</strong> {loan.term_sheet_url ? '✅ Yes' : '❌ No'}</p>
                  <p><strong>Current Step:</strong> {loan.current_step || 'N/A'}</p>
                  <p><strong>Is Ops View:</strong> {isOpsView ? '✅ Yes' : '❌ No'}</p>
                  <p><strong>Should Show Sign Card:</strong> {
                    ((loan.status === "soft_quote_issued" || 
                      loan.status === "soft_quote" || 
                      (loan.soft_quote_generated && !loan.term_sheet_signed)) && 
                      !loan.term_sheet_signed && 
                      !isOpsView) ? '✅ YES' : '❌ NO'
                  }</p>
                </CardContent>
              </Card>
            )}

            {loan.status === "needs_list_sent" && (
              <Card>
                <CardHeader>
                  <CardTitle>Document Upload</CardTitle>
                  <CardDescription>Upload required documents for your loan</CardDescription>
                </CardHeader>
                <CardContent>
                  {needsList.length === 0 ? (
                    <p className="text-muted-foreground">No documents requested yet</p>
                  ) : (
                    <div className="space-y-3">
                      {needsList.map((item) => (
                        <div key={item.id} className="flex items-center justify-between p-3 border rounded-lg">
                          <div>
                            <p className="font-medium">{item.document_type}</p>
                            <p className="text-sm text-muted-foreground">{item.description}</p>
                            {item.document_count > 0 && (
                              <p className="text-xs text-muted-foreground mt-1">
                                {item.document_count} file(s) uploaded
                              </p>
                            )}
                          </div>
                          <label>
                            <input
                              type="file"
                              className="hidden"
                              onChange={async (e) => {
                                const file = e.target.files?.[0];
                                if (file && loanId) {
                                  try {
                                    await documentsApi.upload(loanId, file, item.id);
                                    toast.success("Document uploaded");
                                    await loadLoanData();
                                  } catch (error: any) {
                                    toast.error(error.message || "Upload failed");
                                  }
                                }
                              }}
                            />
                            <Button variant="outline" size="sm" asChild>
                              <span>
                                <Upload className="w-4 h-4 mr-2" /> Upload
                              </span>
                            </Button>
                          </label>
                        </div>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            )}

            {loan.status === "appraisal_ordered" && !loan.appraisal_paid && (
              <Card className="border-orange-500/50 bg-orange-500/5">
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CreditCard className="w-5 h-5 text-orange-600" />
                    Appraisal Payment Required
                  </CardTitle>
                  <CardDescription>
                    Payment is non-refundable. Required to proceed with appraisal.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="mb-4">
                    <p className="text-sm text-muted-foreground">Appraisal Fee</p>
                    <p className="text-2xl font-bold">
                      {formatCurrency(loan.property_type === 'commercial' ? 750 : 500)}
                    </p>
                  </div>
                  <Button variant="gold" onClick={() => setShowAppraisalPayment(true)}>
                    Pay Appraisal Fee
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* Full Application Form */}
            {loan.status === "needs_list_complete" && !loan.full_application_completed && (
              <FullApplicationForm 
                loanId={loanId!} 
                loan={loan} 
                onComplete={loadLoanData}
              />
            )}

            {/* Closing Checklist */}
            {(loan.status === "conditional_commitment_issued" || loan.status === "closing_checklist_issued" || loan.status === "clear_to_close") && closingChecklist.length > 0 && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <ClipboardCheck className="w-5 h-5" />
                    Closing Checklist
                  </CardTitle>
                  <CardDescription>
                    Complete these items before closing
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-3">
                    {closingChecklist.map((item) => (
                      <div 
                        key={item.id} 
                        className={`flex items-start gap-3 p-3 border rounded-lg ${
                          item.completed ? 'bg-muted/50' : ''
                        }`}
                      >
                        <Checkbox
                          checked={item.completed}
                          disabled
                          className="mt-1"
                        />
                        <div className="flex-1">
                          <div className="flex items-center gap-2">
                            <p className={`font-medium ${item.completed ? 'line-through text-muted-foreground' : ''}`}>
                              {item.item_name}
                            </p>
                            {item.required && (
                              <Badge variant="outline" className="text-xs">Required</Badge>
                            )}
                          </div>
                          {item.description && (
                            <p className="text-sm text-muted-foreground mt-1">{item.description}</p>
                          )}
                          {item.completed && item.completed_by_name && (
                            <p className="text-xs text-muted-foreground mt-1">
                              Completed by {item.completed_by_name}
                            </p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                  <div className="mt-4 pt-4 border-t">
                    <p className="text-sm text-muted-foreground">
                      {closingChecklist.filter((item: any) => item.completed).length} of {closingChecklist.length} items completed
                    </p>
                  </div>
                </CardContent>
              </Card>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Loan Progress</CardTitle>
              </CardHeader>
              <CardContent>
                <LoanTrackerFull currentStatus={loan.status as LoanStatus} />
              </CardContent>
            </Card>

            {loan.term_sheet_url && (
              <Card>
                <CardHeader>
                  <CardTitle className="text-base">Downloads</CardTitle>
                </CardHeader>
                <CardContent className="space-y-2">
                  <a href={loan.term_sheet_url} target="_blank" rel="noopener noreferrer">
                    <Button variant="outline" size="sm" className="w-full justify-start">
                      <Download className="w-4 h-4 mr-2" /> Term Sheet
                    </Button>
                  </a>
                  {loan.commitment_letter_url && (
                    <a href={loan.commitment_letter_url} target="_blank" rel="noopener noreferrer">
                      <Button variant="outline" size="sm" className="w-full justify-start">
                        <Download className="w-4 h-4 mr-2" /> Commitment Letter
                      </Button>
                    </a>
                  )}
                </CardContent>
              </Card>
            )}
          </div>
        </div>
      </div>

      {/* Credit Authorization Dialog */}
      <Dialog open={showCreditAuth} onOpenChange={setShowCreditAuth}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Credit Authorization</DialogTitle>
            <DialogDescription>
              Authorize a soft credit pull to generate your loan quote
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-4 bg-muted rounded-lg">
              <p className="text-sm text-muted-foreground mb-2">
                By authorizing this credit check, you agree to:
              </p>
              <ul className="text-sm space-y-1 list-disc list-inside">
                <li>Allow RPC Lending to perform a soft credit inquiry</li>
                <li>Use your credit information to generate a loan quote</li>
                <li>Understand this is a soft pull and will not affect your credit score</li>
              </ul>
            </div>
            <div className="flex items-start space-x-2">
              <Checkbox
                id="consent"
                checked={creditConsent}
                onCheckedChange={(checked) => setCreditConsent(checked as boolean)}
              />
              <Label htmlFor="consent" className="text-sm cursor-pointer">
                I authorize RPC Lending to perform a soft credit pull for the purpose of generating a loan quote.
              </Label>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowCreditAuth(false)}>
              Cancel
            </Button>
            <Button variant="gold" onClick={handleCreditAuth} disabled={!creditConsent || isProcessing}>
              {isProcessing ? "Processing..." : "Authorize & Continue"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Appraisal Payment Dialog */}
      <Dialog open={showAppraisalPayment} onOpenChange={setShowAppraisalPayment}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Appraisal Payment</DialogTitle>
            <DialogDescription>
              Payment is required to proceed with the property appraisal
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="p-4 bg-orange-50 border border-orange-200 rounded-lg">
              <p className="text-sm font-medium text-orange-900 mb-1">Non-Refundable Payment</p>
              <p className="text-xs text-orange-700">
                This payment is non-refundable once the appraisal process begins.
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground mb-1">Amount</p>
              <p className="text-2xl font-bold">
                {formatCurrency(loan.property_type === 'commercial' ? 750 : 500)}
              </p>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAppraisalPayment(false)}>
              Cancel
            </Button>
            <Button variant="gold" onClick={handleAppraisalPayment} disabled={isProcessing}>
              {isProcessing ? "Processing..." : "Pay Now"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

